### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by hanoisteve** [saturnism/grpc-java-by-example#38]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.149 s
[INFO] Finished at: 2019-06-19T15:46:05+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy-dependencies (default) on project simple-grpc-client: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by saturnism** [comment]
not quite sure why this happened for you. i've added maven wrapper, and requiring JDK 11 now. thnx!

**Comment by hanoisteve** [comment]
Yeah, I dont think we use JDK 11 really.
